// actionTypes.js
export const FETCH_EARNINGS_REQUEST = "FETCH_EARNINGS_REQUEST";
export const FETCH_EARNINGS_SUCCESS = "FETCH_EARNINGS_SUCCESS";
export const FETCH_EARNINGS_FAILURE = "FETCH_EARNINGS_FAILURE";

export const FETCH_BOOKINGS_REQUEST = "FETCH_BOOKINGS_REQUEST";
export const FETCH_BOOKINGS_SUCCESS = "FETCH_BOOKINGS_SUCCESS";
export const FETCH_BOOKINGS_FAILURE = "FETCH_BOOKINGS_FAILURE";
