export const FETCH_NOTIFICATIONS_REQUEST = "FETCH_NOTIFICATIONS_REQUEST";
export const FETCH_NOTIFICATIONS_SUCCESS = "FETCH_NOTIFICATIONS_SUCCESS";
export const FETCH_NOTIFICATIONS_FAILURE = "FETCH_NOTIFICATIONS_FAILURE";

export const FETCH_NOTIFICATIONS_BY_USER_REQUEST = "FETCH_NOTIFICATIONS_BY_USER_REQUEST";
export const FETCH_NOTIFICATIONS_BY_USER_SUCCESS = "FETCH_NOTIFICATIONS_BY_USER_SUCCESS";
export const FETCH_NOTIFICATIONS_BY_USER_FAILURE = "FETCH_NOTIFICATIONS_BY_USER_FAILURE";

export const FETCH_NOTIFICATIONS_BY_SALON_REQUEST = "FETCH_NOTIFICATIONS_BY_SALON_REQUEST";
export const FETCH_NOTIFICATIONS_BY_SALON_SUCCESS = "FETCH_NOTIFICATIONS_BY_SALON_SUCCESS";
export const FETCH_NOTIFICATIONS_BY_SALON_FAILURE = "FETCH_NOTIFICATIONS_BY_SALON_FAILURE";

export const CREATE_NOTIFICATION_REQUEST = "CREATE_NOTIFICATION_REQUEST";
export const CREATE_NOTIFICATION_SUCCESS = "CREATE_NOTIFICATION_SUCCESS";
export const CREATE_NOTIFICATION_FAILURE = "CREATE_NOTIFICATION_FAILURE";

export const MARK_NOTIFICATION_AS_READ_REQUEST = "MARK_NOTIFICATION_AS_READ_REQUEST";
export const MARK_NOTIFICATION_AS_READ_SUCCESS = "MARK_NOTIFICATION_AS_READ_SUCCESS";
export const MARK_NOTIFICATION_AS_READ_FAILURE = "MARK_NOTIFICATION_AS_READ_FAILURE";

export const DELETE_NOTIFICATION_REQUEST = "DELETE_NOTIFICATION_REQUEST";
export const DELETE_NOTIFICATION_SUCCESS = "DELETE_NOTIFICATION_SUCCESS";
export const DELETE_NOTIFICATION_FAILURE = "DELETE_NOTIFICATION_FAILURE";

export const ADD_NOTIFICATION="ADD_NOTIFICATION";
