server:
  port: 5003

#database comfirguration
spring:
  application:
    name: booking

  datasource:
    url: "jdbc:mysql://localhost:3304/salon_bookingdb?createDatabaseIfNotExist=true"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#  rabbitmq:
#    port: 5672
#    host: localhost
#    username: guest
#    password: guest

#for mai
  mail:
    host: smtp.gmail.com
    port: 587
    username: saurabhwanjari774@gmail.com
    password: qbij ivdv lenp vmrb
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: read_only
    health:
      probes:
        enabled: true

  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

razorpay:
  api:
    key: rzp_test_p05gsP0O9199nI
    secret: rklxNAQymw4rgmkQMRRgw4An

stripe:
  api:
    key: sk_test_51OY24RHktfaHaMpma35wc5WWVeCTtr23N5crNHIT0RkFlc7tQkAqdoH09x4QbHOfZfQf6MIvcio4lTJFllnOxGxj00dI1RvRn5

#for eureka and service discovery

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/




#for doc generation
info:
  app:
    name: "Payment Service"
    description: "Payment Service API For Salon Booking System"
    version: "1.0.0"